stages:
  - deploy
deploy:
  stage: deploy
  environment: api
  script:
    - echo "deploy ing...";
    - curl "http://webhook.vrcdkj.cn/deploy.php?branch=master&env=fdev&access_token=none"
  only:
    - master